/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HealthcareInterface.doctor;

import healthcare.enterprise.Enterprise;
import healthcare.network.Network;
import healthcare.userAccount.UserAccount;
import healthcare.workQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tejas
 */
public class ViewLabResults extends javax.swing.JPanel {

    /**
     * Creates new form ViewLabResults
     */
    

    WorkRequest patientrequest;
    Network network;
    Enterprise enterprise;
    UserAccount userAccount;
    String emailId=null;
    
    public ViewLabResults(WorkRequest request, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.patientrequest = request;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        popupResult();
    }
    
    
     private void popupResult() {
        System.out.println("ekrhvbevr---------------------");
        System.out.println(patientrequest.getSender().getUserName());
        System.out.println(patientrequest.getLabresult());
        System.out.println(patientrequest.getResulttype());
        System.out.println(patientrequest.getSolution());
        
        txtName.setText(patientrequest.getSender().getUserName());
        resulttxt.setText(patientrequest.getLabresult());
        resultTypetxt.setText(patientrequest.getResulttype());
        solutionByLabtxt.setText(patientrequest.getSolution());
        txtDocDiagnosis.setText(patientrequest.getDiagnose());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        optionPanel = new javax.swing.JPanel();
        prescriptionBtn = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resulttxt = new javax.swing.JTextField();
        result_txt = new javax.swing.JLabel();
        result_txt2 = new javax.swing.JLabel();
        resultTypetxt = new javax.swing.JTextField();
        result_txt1 = new javax.swing.JLabel();
        solutionByLabtxt = new javax.swing.JTextField();
        txtDocDiagnosis = new javax.swing.JTextField();
        diagnosisbtn = new javax.swing.JButton();

        optionPanel.setBackground(new java.awt.Color(255, 204, 204));

        prescriptionBtn.setBackground(new java.awt.Color(153, 204, 255));
        prescriptionBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        prescriptionBtn.setText("Write Prescription");
        prescriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prescriptionBtn)
                .addContainerGap())
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(prescriptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(optionPanel);

        actionPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lab Process Result");

        resulttxt.setEditable(false);

        result_txt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        result_txt.setText("Result");

        result_txt2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        result_txt2.setText("Result Type");

        resultTypetxt.setEditable(false);

        result_txt1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        result_txt1.setText("Solution By Lab");

        solutionByLabtxt.setEditable(false);

        diagnosisbtn.setText("Add Diagnosis");
        diagnosisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(result_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(result_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resulttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(result_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solutionByLabtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(txtDocDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(diagnosisbtn)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resulttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solutionByLabtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(actionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void prescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionBtnActionPerformed
        // TODO add your handling code here:

        RequestPharmacistForMedicinePanel medPanel = new RequestPharmacistForMedicinePanel(patientrequest, network, userAccount, enterprise);
        jSplitPane1.setRightComponent(medPanel);

       // JOptionPane.showMessageDialog(null, "Request sent back to Doctor");

    }//GEN-LAST:event_prescriptionBtnActionPerformed

    private void diagnosisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisbtnActionPerformed
        // TODO add your handling code here:
        patientrequest.setDiagnose(txtDocDiagnosis.getText());
        txtDocDiagnosis.setText("");
        JOptionPane.showMessageDialog(null, "Diagnosis Added Successfully");
    }//GEN-LAST:event_diagnosisbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton diagnosisbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton prescriptionBtn;
    private javax.swing.JTextField resultTypetxt;
    private javax.swing.JLabel result_txt;
    private javax.swing.JLabel result_txt1;
    private javax.swing.JLabel result_txt2;
    private javax.swing.JTextField resulttxt;
    private javax.swing.JTextField solutionByLabtxt;
    private javax.swing.JTextField txtDocDiagnosis;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
