/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DonorBankInterface.donorAdmin;

import userinterface.SupplyChainInterface.supplyManger.*;
import healthcare.Ecosystem;
import healthcare.enterprise.donorBank.DonationHandlerRole;
import healthcare.enterprise.pharmacy.PharmacistRole;
import healthcare.enterprise.supplyChain.HandlerRole;
import healthcare.organization.Organization;
import healthcare.organization.OrganizationDirectory;
import healthcare.person.Person;
import healthcare.userAccount.UserAccount;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import userinterface.SendMail;

/**
 *
 * @author adity
 */
public class DonationHandlerSignUp extends javax.swing.JPanel {

    /**
     * Creates new form HandlerSignUp
     */
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    Ecosystem ecosystem;  
    OrganizationDirectory orgList;
    public DonationHandlerSignUp(Ecosystem ecosystem, OrganizationDirectory orgList) {
        initComponents();
        this.ecosystem = ecosystem;
        this.orgList = orgList;
        populateOrganizationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDateOfBirth = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblPhoneNo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        cboxGender = new javax.swing.JComboBox<>();
        lblState = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        lblOrgName = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDateOfBirth.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblDateOfBirth.setText("Date Of Birth");
        add(lblDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 230, -1));
        add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 230, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 230, -1));

        lblTitle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Handler Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 610, 30));
        add(txtZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 230, -1));

        btnSignUp.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 590, -1, -1));

        lblPhoneNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblPhoneNo.setText("Phone No.");
        add(lblPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));

        lblName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, -1, -1));

        lblUsername.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblUsername.setText("Email");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, -1, -1));

        lblGender.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblGender.setText("Gender");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, -1));

        cboxGender.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        add(cboxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 230, -1));

        lblState.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblState.setText("State");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, -1, -1));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 230, -1));

        lblCity.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, -1, -1));

        lblZipCode.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblZipCode.setText("Zipcode");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, -1, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 230, -1));

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 230, -1));

        lblAddress.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblAddress.setText("Address");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, -1, -1));

        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 230, -1));

        lblOrgName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblOrgName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrgName.setText("Organization Name");
        add(lblOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 134, -1));

        organizationJComboBox.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor", "Nurse", "Patient" }));
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DonorCreate.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        try{
            if(EmpytyFieldValidation()){

                if(RegexValidation()){

                    String name = txtName.getText();
                    long cellPhoneNumber = Long.parseLong(txtPhoneNo.getText());
                    String emailId = txtEmail.getText();
                    String gender = cboxGender.getSelectedItem().toString();
                    
                    String dob = txtDateOfBirth.getText();
                    String Address = txtAddress.getText();
                    String City = txtCity.getText();
                    String State = txtState.getText();
                    long Zipcode = Long.parseLong(txtZipcode.getText());
                    
                    Random random=new Random();
                    int HandlerID=random.nextInt((9999 - 100) + 1) + 10;
                    
                    Organization organization = (Organization) organizationJComboBox.getSelectedItem();
                    
                    String username = name.substring(0, 3) + String.valueOf(HandlerID);
                    String password = name + String.valueOf(random.nextInt((9999 - 100) + 1) + 10);
                    
                    Person p = organization.getPersonDirectory().createAndAddPerson(name, Address, City, State, Zipcode, cellPhoneNumber);  
                    UserAccount u = organization.getUserAccountDirectory().createUserAccount(HandlerID,username, password, p, new DonationHandlerRole(), emailId);
                    
                    JOptionPane.showMessageDialog(this,"Handler Registered Successfully.Your New Username is:"+username+" and password: "+password+",Please save this Id for furture reference.");
                    
                    SendMail s = new SendMail();
                    s.sendUserRegisterEmail(emailId, username, password);

                }
                else{
                    JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                    validationCheck=true;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Some Error in entered data. Please check over the red fields to know more.");
                emptyValidationStatus=true;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Handler not registered, Try again");
            System.out.println(e.toString());
            emptyValidationStatus=true;
        }
    }                                               

    private boolean RegexValidation() {
        if(!txtName.getText().matches("^[a-zA-Z ]+$"))
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtName.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(txtName.getText().matches("^[a-zA-Z ]+$"))
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$"))
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtEmail.setToolTipText("Please enter a valid Email Address in the form abc@xyy.com");
            validationCheck=false;
        }
        
        if(txtEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$"))
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            validationCheck=true;
        }
        
        if(!txtPhoneNo.getText().matches("^[0-9]{10}$"))
        {
            txtPhoneNo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtPhoneNo.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }
        
        if(txtPhoneNo.getText().matches("^[0-9]{10}$"))
        {
            txtPhoneNo.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            validationCheck=true;
        }

        if(!txtAddress.getText().matches("^[a-zA-Z ]+$"))
        {
            txtAddress.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtAddress.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(txtAddress.getText().matches("^[a-zA-Z ]+$"))
        {
            txtAddress.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtCity.getText().matches("^[a-zA-Z ]+$"))
        {
            txtCity.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtCity.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(txtCity.getText().matches("^[a-zA-Z ]+$"))
        {
            txtCity.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtState.getText().matches("^[a-zA-Z ]+$"))
        {
            txtState.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtState.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(txtState.getText().matches("^[a-zA-Z ]+$"))
        {
            txtState.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtDateOfBirth.getText().matches("^(1[0-2]|0[1-9])/(3[01]" + "|[12][0-9]|0[1-9])/[0-9]{4}$"))
        {
            txtDateOfBirth.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDateOfBirth.setToolTipText("Please enter in format mm/dd/yyyy");
            validationCheck=false;
        }
        
        if(txtDateOfBirth.getText().matches("^(1[0-2]|0[1-9])/(3[01]" + "|[12][0-9]|0[1-9])/[0-9]{4}$"))
        {
            txtDateOfBirth.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtZipcode.getText().matches("^[0-9]{5}(?:-[0-9]{4})?$"))
        {
            txtZipcode.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtZipcode.setToolTipText("Please enter a valid zip code number");
            validationCheck=false;
        }
         if(txtZipcode.getText().matches("^[0-9]{5}(?:-[0-9]{4})?$"))
        {
            txtZipcode.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            validationCheck=true;
        }

        return validationCheck;
    }
    
    private boolean EmpytyFieldValidation() {
        if(txtName.getText().equals(null) || txtName.getText().trim().isEmpty() )
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtName.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtName.getText().equals(null) && !txtName.getText().trim().isEmpty() )
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
       
        if(txtAddress.getText().equals(null)|| txtAddress.getText().trim().isEmpty())
        {
            txtAddress.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtAddress.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtAddress.getText().equals(null) && !txtAddress.getText().trim().isEmpty())
        {
            txtAddress.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
           emptyValidationStatus= true;
        }
        
        if(txtCity.getText().equals(null)|| txtCity.getText().trim().isEmpty())
        {
            txtCity.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtCity.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtCity.getText().equals(null) && !txtCity.getText().trim().isEmpty())
        {
            txtCity.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
           emptyValidationStatus= true;
        }
        
        if(txtPhoneNo.getText().equals(null) || txtPhoneNo.getText().trim().isEmpty())
        {
            txtPhoneNo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtPhoneNo.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus=false;
        }
        if(!txtPhoneNo.getText().equals(null) && !txtPhoneNo.getText().trim().isEmpty())
        {
            txtPhoneNo.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
        
        if(txtEmail.getText().equals(null)|| txtEmail.getText().trim().isEmpty())
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtEmail.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtEmail.getText().equals(null) && !txtEmail.getText().trim().isEmpty())
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
           
        }
        if(txtDateOfBirth.getText().equals(null)|| txtDateOfBirth.getText().trim().isEmpty())
        {
            txtDateOfBirth.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDateOfBirth.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtDateOfBirth.getText().equals(null) && !txtDateOfBirth.getText().trim().isEmpty())
        {
            txtDateOfBirth.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
           emptyValidationStatus= true;
        }
        
        if(txtState.getText().equals(null)|| txtState.getText().trim().isEmpty())
        {
            txtState.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtState.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtState.getText().equals(null) && !txtState.getText().trim().isEmpty())
        {
            txtState.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
        
        if(txtZipcode.getText().equals(null)|| txtZipcode.getText().trim().isEmpty())
        {
            txtZipcode.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtZipcode.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtZipcode.getText().equals(null) && !txtZipcode.getText().trim().isEmpty())
        {
            txtZipcode.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
        return emptyValidationStatus;
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : orgList.getOrganizationList()) {
            organizationJComboBox.addItem(organization);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cboxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
