/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Vaccination.vaccinator;

import userinterface.SupplyChainInterface.handler.*;
import userinterface.Pharmacy.pharmacist.*;
import userinterface.LabInterface.labTech.*;
import healthcare.enterprise.Enterprise;
import healthcare.enterprise.healthCare.DoctorOrganization;
import healthcare.enterprise.healthCare.HealthCareEnterprise;
import healthcare.enterprise.pharmacy.PharmacyOrganization;
import healthcare.enterprise.supplyChain.SupplierOrganization;
import healthcare.enterprise.vaccination.VaccinationEnterprise;
import healthcare.enterprise.vaccination.VaccinationOrganization;
import healthcare.network.Network;
import healthcare.organization.Organization;
import healthcare.userAccount.UserAccount;
import healthcare.workQueue.DoctorLabRequest;
import healthcare.workQueue.WorkRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author adity
 */
public class ProcessVaccinationRequest extends javax.swing.JPanel {

    /**
     * Creates new form CollectedMedicalHistory
     */
    
    WorkRequest request;
    UserAccount useraccount;
    Enterprise enterprise;
    Network network;
    String result = "";
    String solution = "";
    String type = "";
    
    public ProcessVaccinationRequest(WorkRequest request,UserAccount useraccount, Enterprise enterprise, Network network) {
        initComponents();
        this.request = request;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.network = network;
        populateVaccinationRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSendResults = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chkTdap = new javax.swing.JCheckBox();
        chkPolio = new javax.swing.JCheckBox();
        chkMMR = new javax.swing.JCheckBox();
        chkVar = new javax.swing.JCheckBox();
        chkCov = new javax.swing.JCheckBox();

        jLabel6.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vaccination Request Details");

        btnSendResults.setText("Process And Send Results");
        btnSendResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendResultsActionPerformed(evt);
            }
        });

        txtPatientName.setBackground(new java.awt.Color(153, 204, 255));
        txtPatientName.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtPatientName.setEnabled(false);
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Request By");

        chkTdap.setBackground(new java.awt.Color(255, 204, 204));
        chkTdap.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chkTdap.setText("T-Dap ");
        chkTdap.setEnabled(false);
        chkTdap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTdapActionPerformed(evt);
            }
        });

        chkPolio.setBackground(new java.awt.Color(255, 204, 204));
        chkPolio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chkPolio.setText("Polio");
        chkPolio.setEnabled(false);
        chkPolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPolioActionPerformed(evt);
            }
        });

        chkMMR.setBackground(new java.awt.Color(255, 204, 204));
        chkMMR.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chkMMR.setText("MMR");
        chkMMR.setEnabled(false);
        chkMMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMMRActionPerformed(evt);
            }
        });

        chkVar.setBackground(new java.awt.Color(255, 204, 204));
        chkVar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chkVar.setText("Varicella");
        chkVar.setEnabled(false);
        chkVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVarActionPerformed(evt);
            }
        });

        chkCov.setBackground(new java.awt.Color(255, 204, 204));
        chkCov.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chkCov.setText("Covishield");
        chkCov.setEnabled(false);
        chkCov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendResults, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkMMR)
                    .addComponent(chkPolio)
                    .addComponent(chkTdap)
                    .addComponent(chkCov)
                    .addComponent(chkVar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(chkTdap)
                .addGap(30, 30, 30)
                .addComponent(chkPolio)
                .addGap(32, 32, 32)
                .addComponent(chkMMR)
                .addGap(27, 27, 27)
                .addComponent(chkVar)
                .addGap(29, 29, 29)
                .addComponent(chkCov)
                .addGap(27, 27, 27)
                .addComponent(btnSendResults)
                .addGap(104, 104, 104))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(404, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendResultsActionPerformed
        // TODO add your handling code here:

      //  txtLabAssesmentsResults.setText(result);
        /*-----------------------*/
        int b = request.getHashcode();
        System.out.println("b" + b);
        //Dharati
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;
        
        for (Enterprise ent : network.getEnterpriseMasterList().getEnterpriseList()) {
            if (ent instanceof VaccinationEnterprise) {
                for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof VaccinationOrganization ){
                        for (WorkRequest work : organization.getWorkQueue().getWorkRequestList()) {
                            if (work.getHashcode() == b) {
                                work.setStatus("Vaccination Req Done");
                            }
                        }
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(null, "Vaccines supplied Successfully");
        
    }//GEN-LAST:event_btnSendResultsActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void chkTdapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTdapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTdapActionPerformed

    private void chkPolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPolioActionPerformed

    private void chkMMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMMRActionPerformed

    private void chkVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVarActionPerformed

    private void chkCovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCovActionPerformed

    
    public void populateVaccinationRequests() {

       String vacList = request.getVaccinesList();
        
        if(vacList.contains(String.valueOf("T-Dap"))){
            chkTdap.setSelected(true);
        }
        if(vacList.contains(String.valueOf("Polio"))){
            chkPolio.setSelected(true);
        }
        if(vacList.contains(String.valueOf("MMR"))){
            chkMMR.setSelected(true);
        }
        if(vacList.contains(String.valueOf("Varicella"))){
            chkVar.setSelected(true);
        }
        if(vacList.contains(String.valueOf("Covishield"))){
            chkCov.setSelected(true);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendResults;
    private javax.swing.JCheckBox chkCov;
    private javax.swing.JCheckBox chkMMR;
    private javax.swing.JCheckBox chkPolio;
    private javax.swing.JCheckBox chkTdap;
    private javax.swing.JCheckBox chkVar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
