/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DonorBankInterface.donationHandler;

import healthcare.Ecosystem;
import healthcare.Enterprise.donorBank.DonorBankOrganization;
import healthcare.Enterprise.donorBank.DonorRole;
import healthcare.enterprise.Enterprise;
import healthcare.enterprise.healthCare.DoctorOrganization;
import healthcare.enterprise.healthCare.DoctorRole;
import healthcare.network.Network;
import healthcare.organization.Organization;
import healthcare.organization.OrganizationDirectory;
import healthcare.person.Person;
import healthcare.role.Role;
import healthcare.userAccount.UserAccount;
import java.awt.Color;
import java.util.HashSet;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import userinterface.SendMail;

/**
 *
 * @author shriyapandita
 */
public class DonationForm extends javax.swing.JPanel {

    /**
     * Creates new form DonationForm
     */
    private DonorBankOrganization organization;
    Ecosystem ecosystem;
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    public DonationForm(Ecosystem ecosystem, UserAccount account,
            Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.organization = (DonorBankOrganization) organization;
        this.ecosystem= ecosystem;
        //populateOrganizationComboBox(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDonorName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDateofBirth = new javax.swing.JTextField();
        cboxBlood = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboxDiseases = new javax.swing.JComboBox<>();
        cboxAllergies = new javax.swing.JComboBox<>();
        cboxDonate = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cboxPreviousOrganDonation = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Donor Name");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Date of Birth");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Email");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Phone");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Occupation");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Blood Type");

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel10.setText("Did you ever donate blood before?");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel11.setText("Do you suffer of any diseases?");

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel12.setText("Do you have any allergies?");

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setText("General Details");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateofBirthActionPerformed(evt);
            }
        });

        cboxBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        cboxBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBloodActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setText("Additional Details");

        txtOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOccupationActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Blood Donation Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addComponent(jLabel1)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel1)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        cboxDiseases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cboxDiseases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDiseasesActionPerformed(evt);
            }
        });

        cboxAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cboxAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxAllergiesActionPerformed(evt);
            }
        });

        cboxDonate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cboxDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDonateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel15.setText("Did you ever donate organ before?");

        cboxPreviousOrganDonation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cboxPreviousOrganDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPreviousOrganDonationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6))
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSubmit)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboxDonate, 0, 223, Short.MAX_VALUE)
                            .addComponent(cboxDiseases, 0, 223, Short.MAX_VALUE)
                            .addComponent(cboxAllergies, 0, 223, Short.MAX_VALUE)
                            .addComponent(cboxPreviousOrganDonation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cboxBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboxDonate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cboxPreviousOrganDonation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboxDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboxAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateofBirthActionPerformed

    private void cboxBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxBloodActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try {
            if (EmpytyFieldValidation()) {

                if (RegexValidation()) {

                    String name = txtDonorName.getText();
                    String emailId = txtEmail.getText();
                    long cellPhoneNumber = Long.parseLong(txtPhone.getText());
                    
                    Random random = new Random();
                    int donorID = random.nextInt((9999 - 100) + 1) + 10;

                    String username = name.substring(0, 3) + String.valueOf(donorID);
                    String password = name + String.valueOf(random.nextInt((9999 - 100) + 1) + 10);
                    
                    DonorRole role  = new DonorRole();
                    role.setBloodType(cboxBlood.getSelectedItem().toString());
                    role.setBlooddonate(cboxDonate.getSelectedItem().toString());
                    role.setPreviousOrgDonation(cboxPreviousOrganDonation.getSelectedItem().toString());
                    role.setPriorallergies(cboxAllergies.getSelectedItem().toString());
                    role.setSufferdisease(cboxDiseases.getSelectedItem().toString());
                    role.setOccupation(txtOccupation.toString());
                    role.setDateofbirth(txtDateofBirth.toString());
                            
                    Person p = organization.getPersonDirectory().createAndAddDonor(name, cellPhoneNumber);           
                    UserAccount account = organization.getUserAccountDirectory().createUserAccount(donorID,username, password, p, role, emailId);
                    
                    JOptionPane.showMessageDialog(this, "Blood Donor Registered Successfully.Your New Username:" + username + " and password: " + password + ",Please save this Id for furture reference.");

                    SendMail s = new SendMail();
                    s.sendUserRegisterEmail(emailId, username, password);

                } else {
                    JOptionPane.showMessageDialog(this, "Some Error in entered data.Please check over the red fields to know more.");
                    validationCheck = true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Some Error in entered data. Please check over the red fields to know more.");
                emptyValidationStatus = true;
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Donor not registered, Try again");
            System.out.println(e.toString());
            emptyValidationStatus = true;
        }
                                                
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOccupationActionPerformed

    private void cboxDiseasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDiseasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxDiseasesActionPerformed

    private void cboxAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxAllergiesActionPerformed

    private void cboxDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDonateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxDonateActionPerformed

    private void cboxPreviousOrganDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPreviousOrganDonationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPreviousOrganDonationActionPerformed

    private boolean RegexValidation() {
        if(!txtDonorName.getText().matches("^[a-zA-Z ]+$"))
        {
            txtDonorName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDonorName.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(txtDonorName.getText().matches("^[a-zA-Z ]+$"))
        {
            txtDonorName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtPhone.getText().matches("\\d{10}"))
        {
          txtPhone.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
          txtPhone.setToolTipText("Please enter valid 10 digit phone number");
          validationCheck=false;
        }
        
        if(txtPhone.getText().matches("\\d{10}"))
        {
            txtPhone.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
            validationCheck=true;
        }
        
        if(!txtEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$"))
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtEmail.setToolTipText("Please enter a valid Email Address in the form abc@xyy.com");
            validationCheck=false;
        }
        
        if(txtEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$"))
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
             validationCheck=true;
        }
        
        if(!txtOccupation.getText().matches("^[a-zA-Z ]+$"))
        {
            txtOccupation.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtOccupation.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(txtOccupation.getText().matches("^[a-zA-Z ]+$"))
        {
            txtOccupation.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
             validationCheck=true;
        }
        
        
        if(!txtDateofBirth.getText().matches("^(1[0-2]|0[1-9])/(3[01]" + "|[12][0-9]|0[1-9])/[0-9]{4}$"))
        {
            txtDateofBirth.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDateofBirth.setToolTipText("Please enter in format mm/dd/yyyy");
            validationCheck=false;
        }
        
        if(txtDateofBirth.getText().matches("^(1[0-2]|0[1-9])/(3[01]" + "|[12][0-9]|0[1-9])/[0-9]{4}$"))
        {
            txtDateofBirth.setBorder(BorderFactory.createLineBorder(Color.BLUE, 0));
             validationCheck=true;
        }
    
        return validationCheck;
    }
    
      //  private void populateOrganizationComboBox() {
      //  cboxBlood.removeAllItems();

      //  for (Organization organization : orgList.getOrganizationList()){
          //   cboxBlood.addItem(organization);
      //  }
  //  }
        
        private boolean EmpytyFieldValidation() {
        if( txtDonorName.getText().equals(null) ||  txtDonorName.getText().trim().isEmpty() )
        {
             txtDonorName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
             txtDonorName.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtDonorName.getText().equals(null) && ! txtDonorName.getText().trim().isEmpty() )
        {
             txtDonorName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
             emptyValidationStatus= true;
        }
        
        if( txtEmail.getText().equals(null) || txtEmail.getText().trim().isEmpty() )
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtEmail.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        
        if( !txtEmail.getText().equals(null) || txtEmail.getText().trim().isEmpty() )
        {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
      
        if( txtOccupation.getText().equals(null) || txtOccupation.getText().trim().isEmpty() )
        {
            txtOccupation.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtOccupation.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        
        if( !txtOccupation.getText().equals(null) || txtOccupation.getText().trim().isEmpty() )
        {
            txtOccupation.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
        
        if( txtDateofBirth.getText().equals(null) || txtDateofBirth.getText().trim().isEmpty() )
        {
            txtDateofBirth.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDateofBirth.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        
        if( !txtDateofBirth.getText().equals(null) || txtDateofBirth.getText().trim().isEmpty() )
        {
            txtDateofBirth.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
      
        if( txtPhone.getText().equals(null) || txtPhone.getText().trim().isEmpty() )
        {
            txtPhone.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtPhone.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        
        if( !txtPhone.getText().equals(null) || txtPhone.getText().trim().isEmpty() )
        {
            txtPhone.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            emptyValidationStatus= true;
        }
      
        return emptyValidationStatus;
    
    }                                
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboxAllergies;
    private javax.swing.JComboBox<String> cboxBlood;
    private javax.swing.JComboBox<String> cboxDiseases;
    private javax.swing.JComboBox<String> cboxDonate;
    private javax.swing.JComboBox<String> cboxPreviousOrganDonation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDonorName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
