/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SupplyChainInterface.handler;

import userinterface.Pharmacy.pharmacist.*;
import userinterface.LabInterface.labTech.*;
import healthcare.enterprise.Enterprise;
import healthcare.enterprise.healthCare.DoctorOrganization;
import healthcare.enterprise.healthCare.HealthCareEnterprise;
import healthcare.enterprise.pharmacy.PharmacyOrganization;
import healthcare.enterprise.supplyChain.SupplierOrganization;
import healthcare.enterprise.supplyChain.SupplyChainEnterprise;
import healthcare.network.Network;
import healthcare.organization.Organization;
import healthcare.userAccount.UserAccount;
import healthcare.workQueue.DoctorLabRequest;
import healthcare.workQueue.WorkRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author adity
 */
public class ProcessSupplyRequest extends javax.swing.JPanel {

    /**
     * Creates new form CollectedMedicalHistory
     */
    
    WorkRequest request;
    UserAccount useraccount;
    Enterprise enterprise;
    Network network;
    String result = "";
    String solution = "";
    String type = "";
    
    public ProcessSupplyRequest(WorkRequest request,UserAccount useraccount, Enterprise enterprise, Network network) {
        initComponents();
        this.request = request;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.network = network;
        populateSupplierRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSendResults = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chkO2 = new javax.swing.JCheckBox();
        chkSin = new javax.swing.JCheckBox();
        chkViv = new javax.swing.JCheckBox();
        chkAnt = new javax.swing.JCheckBox();
        chkCam = new javax.swing.JCheckBox();
        chkDis = new javax.swing.JCheckBox();
        chkAca = new javax.swing.JCheckBox();
        chkCrocin = new javax.swing.JCheckBox();
        chkMef = new javax.swing.JCheckBox();
        chkSpasm = new javax.swing.JCheckBox();
        chkAld = new javax.swing.JCheckBox();
        chkMet = new javax.swing.JCheckBox();
        chkLosa = new javax.swing.JCheckBox();
        chkAlbu = new javax.swing.JCheckBox();
        chkHydro = new javax.swing.JCheckBox();
        chkAntihis = new javax.swing.JCheckBox();
        chkDolo = new javax.swing.JCheckBox();
        chkOme = new javax.swing.JCheckBox();

        jLabel6.setText("jLabel6");

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharma Request Details");

        btnSendResults.setBackground(new java.awt.Color(153, 204, 255));
        btnSendResults.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSendResults.setText("Process And Send Results");
        btnSendResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendResultsActionPerformed(evt);
            }
        });

        txtPatientName.setEditable(false);
        txtPatientName.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtPatientName.setEnabled(false);
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setText("For Pharmacy");

        chkO2.setBackground(new java.awt.Color(255, 204, 204));
        chkO2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkO2.setText("O2");
        chkO2.setEnabled(false);

        chkSin.setBackground(new java.awt.Color(255, 204, 204));
        chkSin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkSin.setText("Sinarest");
        chkSin.setEnabled(false);
        chkSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSinActionPerformed(evt);
            }
        });

        chkViv.setBackground(new java.awt.Color(255, 204, 204));
        chkViv.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkViv.setText(" Vivitrol");
        chkViv.setEnabled(false);
        chkViv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVivActionPerformed(evt);
            }
        });

        chkAnt.setBackground(new java.awt.Color(255, 204, 204));
        chkAnt.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAnt.setText("Antabuse");
        chkAnt.setEnabled(false);
        chkAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntActionPerformed(evt);
            }
        });

        chkCam.setBackground(new java.awt.Color(255, 204, 204));
        chkCam.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkCam.setText("Campral");
        chkCam.setEnabled(false);

        chkDis.setBackground(new java.awt.Color(255, 204, 204));
        chkDis.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkDis.setText("Disulfiram");
        chkDis.setEnabled(false);
        chkDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDisActionPerformed(evt);
            }
        });

        chkAca.setBackground(new java.awt.Color(255, 204, 204));
        chkAca.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAca.setText("Acamprosate");
        chkAca.setEnabled(false);
        chkAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAcaActionPerformed(evt);
            }
        });

        chkCrocin.setBackground(new java.awt.Color(255, 204, 204));
        chkCrocin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkCrocin.setText("Crocin");
        chkCrocin.setEnabled(false);
        chkCrocin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCrocinActionPerformed(evt);
            }
        });

        chkMef.setBackground(new java.awt.Color(255, 204, 204));
        chkMef.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkMef.setText("Meftal");
        chkMef.setEnabled(false);
        chkMef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMefActionPerformed(evt);
            }
        });

        chkSpasm.setBackground(new java.awt.Color(255, 204, 204));
        chkSpasm.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkSpasm.setText("Spasm");
        chkSpasm.setEnabled(false);
        chkSpasm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSpasmActionPerformed(evt);
            }
        });

        chkAld.setBackground(new java.awt.Color(255, 204, 204));
        chkAld.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAld.setText("Aldrid");
        chkAld.setEnabled(false);
        chkAld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAldActionPerformed(evt);
            }
        });

        chkMet.setBackground(new java.awt.Color(255, 204, 204));
        chkMet.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkMet.setText("Metformin");
        chkMet.setEnabled(false);
        chkMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMetActionPerformed(evt);
            }
        });

        chkLosa.setBackground(new java.awt.Color(255, 204, 204));
        chkLosa.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkLosa.setText("Losartan");
        chkLosa.setEnabled(false);
        chkLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLosaActionPerformed(evt);
            }
        });

        chkAlbu.setBackground(new java.awt.Color(255, 204, 204));
        chkAlbu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAlbu.setText("Albuterol");
        chkAlbu.setEnabled(false);
        chkAlbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlbuActionPerformed(evt);
            }
        });

        chkHydro.setBackground(new java.awt.Color(255, 204, 204));
        chkHydro.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkHydro.setText("Hydrocodone");
        chkHydro.setEnabled(false);
        chkHydro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHydroActionPerformed(evt);
            }
        });

        chkAntihis.setBackground(new java.awt.Color(255, 204, 204));
        chkAntihis.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAntihis.setText("Antihistamines");
        chkAntihis.setEnabled(false);
        chkAntihis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntihisActionPerformed(evt);
            }
        });

        chkDolo.setBackground(new java.awt.Color(255, 204, 204));
        chkDolo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkDolo.setText("Dolo");
        chkDolo.setEnabled(false);
        chkDolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDoloActionPerformed(evt);
            }
        });

        chkOme.setBackground(new java.awt.Color(255, 204, 204));
        chkOme.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkOme.setText("Omeprazole");
        chkOme.setEnabled(false);
        chkOme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btnSendResults, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkAca)
                        .addComponent(chkDis)
                        .addComponent(chkCam)
                        .addComponent(chkAnt)
                        .addComponent(chkViv)
                        .addComponent(chkMef))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkHydro)
                        .addComponent(chkDolo)
                        .addComponent(chkO2)
                        .addComponent(chkSin)
                        .addComponent(chkCrocin)
                        .addComponent(chkSpasm))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkOme)
                        .addComponent(chkAlbu)
                        .addComponent(chkLosa)
                        .addComponent(chkMet)
                        .addComponent(chkAld)
                        .addComponent(chkAntihis))
                    .addContainerGap(227, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(317, 317, 317)
                .addComponent(btnSendResults))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkAca)
                        .addComponent(chkHydro)
                        .addComponent(chkAld))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkDis)
                        .addComponent(chkDolo)
                        .addComponent(chkMet))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkCam)
                        .addComponent(chkO2)
                        .addComponent(chkLosa))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkAnt)
                        .addComponent(chkSin)
                        .addComponent(chkAlbu))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkViv)
                        .addComponent(chkCrocin)
                        .addComponent(chkAntihis))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkMef)
                        .addComponent(chkSpasm)
                        .addComponent(chkOme))
                    .addContainerGap(130, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendResultsActionPerformed
        // TODO add your handling code here:

      //  txtLabAssesmentsResults.setText(result);
        /*-----------------------*/
        int b = request.getHashcode();
        System.out.println("b" + b);
        //Dharati
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;
        
        for (Enterprise ent : network.getEnterpriseMasterList().getEnterpriseList()) {
            if (ent instanceof SupplyChainEnterprise) {
                for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof SupplierOrganization ){
                        for (WorkRequest work : organization.getWorkQueue().getWorkRequestList()) {
                            if (work.getHashcode() == b) {
                                work.setStatus("Supplier Req Done");
                            }
                        }
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(null, "Result Sent Successfully");
        
    }//GEN-LAST:event_btnSendResultsActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void chkSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSinActionPerformed

    private void chkVivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVivActionPerformed

    private void chkAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntActionPerformed

    private void chkDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDisActionPerformed

    private void chkAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAcaActionPerformed

    private void chkCrocinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCrocinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCrocinActionPerformed

    private void chkMefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMefActionPerformed

    private void chkSpasmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSpasmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSpasmActionPerformed

    private void chkAldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAldActionPerformed

    private void chkMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMetActionPerformed

    private void chkLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLosaActionPerformed

    private void chkAlbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlbuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAlbuActionPerformed

    private void chkHydroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHydroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHydroActionPerformed

    private void chkAntihisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntihisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntihisActionPerformed

    private void chkDoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDoloActionPerformed

    private void chkOmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOmeActionPerformed

    
    public void populateSupplierRequests() {

       String medList = request.getMedlist();
        
        if(medList.contains(String.valueOf("Disulfiram"))){
            chkDis.setSelected(true);
        }
        if(medList.contains(String.valueOf("Campral"))){
            chkCam.setSelected(true);
        }
        if(medList.contains(String.valueOf("Acamprosate"))){
            chkAca.setSelected(true);
        }
        if(medList.contains(String.valueOf("Antabuse"))){
            chkAnt.setSelected(true);
        }
        if(medList.contains(String.valueOf("Vivitrol"))){
            chkViv.setSelected(true);
        }
   
//-----------------------------------------------------------------------------
        
        if(medList.contains(String.valueOf("Meftal"))){
            chkMef.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Hydrocodone"))){
            chkHydro.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Dolo"))){
            chkDolo.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("O2"))){
            chkO2.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Sinarest"))){
            chkSin.setSelected(true);
        }
        
        
        if(medList.contains(String.valueOf("Crocin"))){
            chkCrocin.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Spasm"))){
            chkSpasm.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Aldrid"))){
            chkAld.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Metformin"))){
            chkMet.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Losartan"))){
            chkLosa.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Albuterol"))){
            chkAlbu.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Antihistamines"))){
            chkAntihis.setSelected(true);
        }
        
        if(medList.contains(String.valueOf("Omeprazole"))){
            chkOme.setSelected(true);
        }
        

//-----------------------------------------------------------------------------

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendResults;
    private javax.swing.JCheckBox chkAca;
    private javax.swing.JCheckBox chkAlbu;
    private javax.swing.JCheckBox chkAld;
    private javax.swing.JCheckBox chkAnt;
    private javax.swing.JCheckBox chkAntihis;
    private javax.swing.JCheckBox chkCam;
    private javax.swing.JCheckBox chkCrocin;
    private javax.swing.JCheckBox chkDis;
    private javax.swing.JCheckBox chkDolo;
    private javax.swing.JCheckBox chkHydro;
    private javax.swing.JCheckBox chkLosa;
    private javax.swing.JCheckBox chkMef;
    private javax.swing.JCheckBox chkMet;
    private javax.swing.JCheckBox chkO2;
    private javax.swing.JCheckBox chkOme;
    private javax.swing.JCheckBox chkSin;
    private javax.swing.JCheckBox chkSpasm;
    private javax.swing.JCheckBox chkViv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
