/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.LabInterface.labTech;

/**
 *
 * @author adity
 */
public class LabTechnicianLabDetails extends javax.swing.JPanel {

    /**
     * Creates new form LabTechnicianLoginScreen
     */
    public LabTechnicianLabDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtReport = new javax.swing.JTextField();
        txtBloodGroup = new javax.swing.JTextField();
        btnSearchByName = new javax.swing.JButton();
        btnAddReport = new javax.swing.JButton();
        btnSearchByBloodGroup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lab Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1250, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Donor name", "ID", "Blood Group", "Type", "Status", "Donor Enterprise", "Receiver Enterprise", "Entity Name", "Report"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1250, 136));

        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        lblReport.setText("Report:");
        add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        lblBloodGroup.setText("Blood Group:");
        add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 212, -1));

        txtReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportActionPerformed(evt);
            }
        });
        add(txtReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 212, -1));
        add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 212, -1));

        btnSearchByName.setText("Search By Name");
        add(btnSearchByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        btnAddReport.setText("Add Report");
        btnAddReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReportActionPerformed(evt);
            }
        });
        add(btnAddReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        btnSearchByBloodGroup.setText("Search By Blood Group");
        add(btnSearchByBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        jButton1.setText("Logout");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ViewLab.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportActionPerformed

    private void btnAddReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReport;
    private javax.swing.JButton btnSearchByBloodGroup;
    private javax.swing.JButton btnSearchByName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReport;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReport;
    // End of variables declaration//GEN-END:variables
}
