/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Pharmacy.pharmacist;

import userinterface.HealthcareInterface.doctor.*;
import healthcare.enterprise.Enterprise;
import healthcare.enterprise.healthCare.DoctorOrganization;
import healthcare.enterprise.pharmacy.PharmacyEnterprise;
import healthcare.enterprise.pharmacy.PharmacyOrganization;
import healthcare.enterprise.supplyChain.SupplierOrganization;
import healthcare.enterprise.supplyChain.SupplyChainEnterprise;
import healthcare.network.Network;
import healthcare.organization.Organization;
import healthcare.userAccount.UserAccount;
import healthcare.workQueue.DoctorLabRequest;
import healthcare.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shriyapandita
 */
public class RequestSupplierForMedicinePanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestPharmacistForMedicinePanel
     */
    private PharmacyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    JPanel userProcessContainer;
    String medlist="";
    
    public RequestSupplierForMedicinePanel( Network network, UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.userAccount = userAccount;
        this.organization = (PharmacyOrganization) organization;
        this.enterprise = enterprise;
        this.network = network;
        txtPharmacistName.setText(userAccount.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtPharmacistName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        requestbtn = new javax.swing.JButton();
        chkViv = new javax.swing.JCheckBox();
        chkAnt = new javax.swing.JCheckBox();
        chkCam = new javax.swing.JCheckBox();
        chkDis = new javax.swing.JCheckBox();
        chkAca = new javax.swing.JCheckBox();
        txtMsg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setText("Supply Chain Request");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 6, -1, -1));

        jButton2.setBackground(new java.awt.Color(71, 120, 197));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 37, 28));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 638, -1));

        txtPharmacistName.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtPharmacistName.setEnabled(false);
        txtPharmacistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacistNameActionPerformed(evt);
            }
        });
        add(txtPharmacistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 52, 205, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("For Pharmacy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 52, 126, 20));

        requestbtn.setBackground(new java.awt.Color(153, 204, 255));
        requestbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        requestbtn.setText("Request Supplier");
        requestbtn.setBorder(null);
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 160, 30));

        chkViv.setBackground(new java.awt.Color(255, 204, 204));
        chkViv.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkViv.setText(" Vivitrol");
        chkViv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVivActionPerformed(evt);
            }
        });
        add(chkViv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        chkAnt.setBackground(new java.awt.Color(255, 204, 204));
        chkAnt.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAnt.setText("Antabuse");
        chkAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntActionPerformed(evt);
            }
        });
        add(chkAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        chkCam.setBackground(new java.awt.Color(255, 204, 204));
        chkCam.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkCam.setText("Campral");
        add(chkCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        chkDis.setBackground(new java.awt.Color(255, 204, 204));
        chkDis.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkDis.setText("Disulfiram");
        chkDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDisActionPerformed(evt);
            }
        });
        add(chkDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        chkAca.setBackground(new java.awt.Color(255, 204, 204));
        chkAca.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAca.setText("Acamprosate");
        chkAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAcaActionPerformed(evt);
            }
        });
        add(chkAca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));
        add(txtMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 338, 205, 32));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Message");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 115, 28));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        WorkRequest request = new WorkRequest();
        request.setSender(userAccount);
       // request.setReceiver();
        if (chkAca.isSelected())
        {
            medlist = medlist + " Acamprosate ,";
        
        }
        if (chkDis.isSelected())
        {
            medlist = medlist + "Disulfiram ,";
        
        }
       
        if(chkCam.isSelected())
        {
            medlist = medlist + "Campral ,";
        }
        if(chkAnt.isSelected())
        {
            medlist = medlist + "Antabuse ,";
        }
        if(chkViv.isSelected())
        {
            medlist = medlist + "Vivitrol ,";
        }
      
        System.out.println(medlist);
        request.setMessage(txtMsg.getText());
        request.setMedlist(medlist);
        request.setStatus("Supply Requested");

        Organization org = null;
        for (Enterprise enterprise : network.getEnterpriseMasterList().getEnterpriseList()) {
            if (enterprise instanceof SupplyChainEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof SupplierOrganization) {
                        org = organization;
                        break;
                    }
                }
            }   
        }

        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            request.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, "Medical prescription sent to pharmacist successfully.");

    }//GEN-LAST:event_requestbtnActionPerformed

    private void chkVivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVivActionPerformed

    private void chkAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntActionPerformed

    private void chkDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDisActionPerformed

    private void chkAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAcaActionPerformed

    private void txtPharmacistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacistNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAca;
    private javax.swing.JCheckBox chkAnt;
    private javax.swing.JCheckBox chkCam;
    private javax.swing.JCheckBox chkDis;
    private javax.swing.JCheckBox chkViv;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton requestbtn;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JTextField txtPharmacistName;
    // End of variables declaration//GEN-END:variables
}
