/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Pharmacy.pharmacist;

import userinterface.HealthcareInterface.doctor.*;
import healthcare.enterprise.Enterprise;
import healthcare.enterprise.healthCare.DoctorOrganization;
import healthcare.enterprise.pharmacy.PharmacyEnterprise;
import healthcare.enterprise.pharmacy.PharmacyOrganization;
import healthcare.enterprise.supplyChain.SupplierOrganization;
import healthcare.enterprise.supplyChain.SupplyChainEnterprise;
import healthcare.network.Network;
import healthcare.organization.Organization;
import healthcare.userAccount.UserAccount;
import healthcare.workQueue.DoctorLabRequest;
import healthcare.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shriyapandita
 */
public class RequestSupplierForMedicinePanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestPharmacistForMedicinePanel
     */
    private PharmacyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    JPanel userProcessContainer;
    String medlist="";
    
    public RequestSupplierForMedicinePanel( Network network, UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.userAccount = userAccount;
        this.organization = (PharmacyOrganization) organization;
        this.enterprise = enterprise;
        this.network = network;
        txtPharmacistName.setText(userAccount.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtPharmacistName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        requestbtn = new javax.swing.JButton();
        chkViv = new javax.swing.JCheckBox();
        chkAnt = new javax.swing.JCheckBox();
        chkCam = new javax.swing.JCheckBox();
        chkDis = new javax.swing.JCheckBox();
        chkAca = new javax.swing.JCheckBox();
        txtMsg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkHydro = new javax.swing.JCheckBox();
        chkDolo = new javax.swing.JCheckBox();
        chkO2 = new javax.swing.JCheckBox();
        chkSin = new javax.swing.JCheckBox();
        chkCrocin = new javax.swing.JCheckBox();
        chkMef = new javax.swing.JCheckBox();
        chkSpasm = new javax.swing.JCheckBox();
        chkAld = new javax.swing.JCheckBox();
        chkMet = new javax.swing.JCheckBox();
        chkLosa = new javax.swing.JCheckBox();
        chkAlbu = new javax.swing.JCheckBox();
        chkAntihis = new javax.swing.JCheckBox();
        chkOme = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 204, 204));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setText("Supply Chain Request");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 6, -1, -1));

        txtPharmacistName.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtPharmacistName.setEnabled(false);
        txtPharmacistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacistNameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("For Pharmacy");

        requestbtn.setBackground(new java.awt.Color(153, 204, 255));
        requestbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        requestbtn.setText("Request Supplier");
        requestbtn.setBorder(null);
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });

        chkViv.setBackground(new java.awt.Color(255, 204, 204));
        chkViv.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkViv.setText(" Vivitrol");
        chkViv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVivActionPerformed(evt);
            }
        });

        chkAnt.setBackground(new java.awt.Color(255, 204, 204));
        chkAnt.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAnt.setText("Antabuse");
        chkAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntActionPerformed(evt);
            }
        });

        chkCam.setBackground(new java.awt.Color(255, 204, 204));
        chkCam.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkCam.setText("Campral");

        chkDis.setBackground(new java.awt.Color(255, 204, 204));
        chkDis.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkDis.setText("Disulfiram");
        chkDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDisActionPerformed(evt);
            }
        });

        chkAca.setBackground(new java.awt.Color(255, 204, 204));
        chkAca.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAca.setText("Acamprosate");
        chkAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAcaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Message");

        chkHydro.setBackground(new java.awt.Color(255, 204, 204));
        chkHydro.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkHydro.setText("Hydrocodone");
        chkHydro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHydroActionPerformed(evt);
            }
        });

        chkDolo.setBackground(new java.awt.Color(255, 204, 204));
        chkDolo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkDolo.setText("Dolo");
        chkDolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDoloActionPerformed(evt);
            }
        });

        chkO2.setBackground(new java.awt.Color(255, 204, 204));
        chkO2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkO2.setText("O2");

        chkSin.setBackground(new java.awt.Color(255, 204, 204));
        chkSin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkSin.setText("Sinarest");
        chkSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSinActionPerformed(evt);
            }
        });

        chkCrocin.setBackground(new java.awt.Color(255, 204, 204));
        chkCrocin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkCrocin.setText("Crocin");
        chkCrocin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCrocinActionPerformed(evt);
            }
        });

        chkMef.setBackground(new java.awt.Color(255, 204, 204));
        chkMef.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkMef.setText("Meftal");
        chkMef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMefActionPerformed(evt);
            }
        });

        chkSpasm.setBackground(new java.awt.Color(255, 204, 204));
        chkSpasm.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkSpasm.setText("Spasm");
        chkSpasm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSpasmActionPerformed(evt);
            }
        });

        chkAld.setBackground(new java.awt.Color(255, 204, 204));
        chkAld.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAld.setText("Aldrid");
        chkAld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAldActionPerformed(evt);
            }
        });

        chkMet.setBackground(new java.awt.Color(255, 204, 204));
        chkMet.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkMet.setText("Metformin");
        chkMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMetActionPerformed(evt);
            }
        });

        chkLosa.setBackground(new java.awt.Color(255, 204, 204));
        chkLosa.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkLosa.setText("Losartan");
        chkLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLosaActionPerformed(evt);
            }
        });

        chkAlbu.setBackground(new java.awt.Color(255, 204, 204));
        chkAlbu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAlbu.setText("Albuterol");
        chkAlbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlbuActionPerformed(evt);
            }
        });

        chkAntihis.setBackground(new java.awt.Color(255, 204, 204));
        chkAntihis.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkAntihis.setText("Antihistamines");
        chkAntihis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntihisActionPerformed(evt);
            }
        });

        chkOme.setBackground(new java.awt.Color(255, 204, 204));
        chkOme.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        chkOme.setText("Omeprazole");
        chkOme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtPharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(requestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAca)
                            .addComponent(chkDis)
                            .addComponent(chkCam)
                            .addComponent(chkAnt)
                            .addComponent(chkViv)
                            .addComponent(chkMef))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkHydro)
                            .addComponent(chkDolo)
                            .addComponent(chkO2)
                            .addComponent(chkSin)
                            .addComponent(chkCrocin)
                            .addComponent(chkSpasm))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkOme)
                            .addComponent(chkAlbu)
                            .addComponent(chkLosa)
                            .addComponent(chkMet)
                            .addComponent(chkAld)
                            .addComponent(chkAntihis))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAca)
                    .addComponent(chkHydro)
                    .addComponent(chkAld))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDis)
                    .addComponent(chkDolo)
                    .addComponent(chkMet))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCam)
                    .addComponent(chkO2)
                    .addComponent(chkLosa))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAnt)
                    .addComponent(chkSin)
                    .addComponent(chkAlbu))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkViv)
                    .addComponent(chkCrocin)
                    .addComponent(chkAntihis))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMef)
                    .addComponent(chkSpasm)
                    .addComponent(chkOme))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(requestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        WorkRequest request = new WorkRequest();
        request.setSender(userAccount);
       // request.setReceiver();
        if (chkAca.isSelected())
        {
            medlist = medlist + " Acamprosate ,";
        
        }
        if (chkDis.isSelected())
        {
            medlist = medlist + "Disulfiram ,";
        
        }
       
        if(chkCam.isSelected())
        {
            medlist = medlist + "Campral ,";
        }
        if(chkAnt.isSelected())
        {
            medlist = medlist + "Antabuse ,";
        }
        if(chkViv.isSelected())
        {
            medlist = medlist + "Vivitrol ,";
        }
        
// ----------------------------------------------------------
        
        if(chkMef.isSelected())
        {
            medlist = medlist + "Meftal ,";
        }
        
        if(chkHydro.isSelected())
        {
            medlist = medlist + "Hydrocodone ,";
        }
        
        if(chkDolo.isSelected())
        {
            medlist = medlist + "Dolo ,";
        }
        
        if(chkO2.isSelected())
        {
            medlist = medlist + "O2 ,";
        }
        
        if(chkSin.isSelected())
        {
            medlist = medlist + "Sinarest ,";
        }
        
        if(chkCrocin.isSelected())
        {
            medlist = medlist + "Crocin ,";
        }
        
        if(chkSpasm.isSelected())
        {
            medlist = medlist + "Spasm ,";
        }
        
        if(chkAld.isSelected())
        {
            medlist = medlist + "Aldrid ,";
        }
        
        if(chkMet.isSelected())
        {
            medlist = medlist + "Metformin ,";
        }
        
        if(chkLosa.isSelected())
        {
            medlist = medlist + "Losartan ,";
        }
        
        if(chkAlbu.isSelected())
        {
            medlist = medlist + "Albuterol ,";
        }
        
        if(chkAntihis.isSelected())
        {
            medlist = medlist + "Antihistamines ,";
        }
        
        if(chkOme.isSelected())
        {
            medlist = medlist + "Omeprazole ,";
        }
        
//-----------------------------------------------------------
      
        System.out.println(medlist);
        request.setMessage(txtMsg.getText());
        request.setMedlist(medlist);
        request.setStatus("Supply Requested");

        Organization org = null;
        for (Enterprise enterprise : network.getEnterpriseMasterList().getEnterpriseList()) {
            if (enterprise instanceof SupplyChainEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof SupplierOrganization) {
                        org = organization;
                        break;
                    }
                }
            }   
        }

        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            request.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, "Med request send to supplier successfully.");

    }//GEN-LAST:event_requestbtnActionPerformed

    private void chkVivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVivActionPerformed

    private void chkAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntActionPerformed

    private void chkDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDisActionPerformed

    private void chkAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAcaActionPerformed

    private void txtPharmacistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacistNameActionPerformed

    private void chkHydroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHydroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHydroActionPerformed

    private void chkDoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDoloActionPerformed

    private void chkSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSinActionPerformed

    private void chkCrocinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCrocinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCrocinActionPerformed

    private void chkMefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMefActionPerformed

    private void chkSpasmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSpasmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSpasmActionPerformed

    private void chkAldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAldActionPerformed

    private void chkMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMetActionPerformed

    private void chkAlbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlbuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAlbuActionPerformed

    private void chkAntihisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntihisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntihisActionPerformed

    private void chkOmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOmeActionPerformed

    private void chkLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLosaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAca;
    private javax.swing.JCheckBox chkAlbu;
    private javax.swing.JCheckBox chkAld;
    private javax.swing.JCheckBox chkAnt;
    private javax.swing.JCheckBox chkAntihis;
    private javax.swing.JCheckBox chkCam;
    private javax.swing.JCheckBox chkCrocin;
    private javax.swing.JCheckBox chkDis;
    private javax.swing.JCheckBox chkDolo;
    private javax.swing.JCheckBox chkHydro;
    private javax.swing.JCheckBox chkLosa;
    private javax.swing.JCheckBox chkMef;
    private javax.swing.JCheckBox chkMet;
    private javax.swing.JCheckBox chkO2;
    private javax.swing.JCheckBox chkOme;
    private javax.swing.JCheckBox chkSin;
    private javax.swing.JCheckBox chkSpasm;
    private javax.swing.JCheckBox chkViv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton requestbtn;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JTextField txtPharmacistName;
    // End of variables declaration//GEN-END:variables
}
